### PR TITLE
Remove unnecessary stuff + button-card code

### PR DESCRIPTION
**Pull request by KTibow**
I haven't implemented it yet, but this is a possibility. Also change triple to single backticks.

### CODE REVIEW

**Comment by N-l1** [comment]
Great, I like the button card code. This way when adding buttons there's no need to install card-mod. Mind implementing the new code to all the buttons. Thanks.

**Comment by KTibow** [comment]
By the way, it's possible to use button cards instead of markdown for headers, but I think you need to disable the tap and hold actions first.

**Comment by KTibow** [comment]
Added! Now to standardize the shadows in another PR...

**Comment by KTibow** [comment]
:relieved:
That's all... :thinking: or is it?

**Pull request merged**
