### PR TITLE
Add Horizontal Buttons With Text Card

### PR DESCRIPTION
**Pull request by KTibow**
I based this off of hawk's post (https://community.home-assistant.io/t/159357/203?u=ktibow).

### CODE REVIEW

**Comment by N-l1** [comment]
The code doesn't seem to work properly 😬

Screen Shot 2020-08-03 at 10 22 49 PM

Another thing, we should probably update the picture for the card. That can be done later though.

**Comment by KTibow** [comment]
I don't know why it doesn't work... Hmm.

**Comment by KTibow** [comment]
Is this better?
```yaml
type: horizontal-stack
cards:
  - aspect_ratio: 1/1
    entity: light.infinity_mirror
    show_state: true
    size: 80%
    state:
      - styles:
          card:
            - border-color: var(--primary-color)
            - border-width: 2px
            - box-shadow: var(--soft-ui-pressed)
          icon:
            - color: var(--primary-color)
          name:
            - color: var(--primary-color)
          state:
            - color: var(--primary-color)
        value: 'on'
    style: |
      #aspect-ratio {
        margin: 10px;
      }
      * {
        --soft-ui-pressed: {% if is_state('sun.sun', 'above_horizon') %}
               inset -4px -4px 8px 0 rgba(255,255,255,.5), inset 4px 4px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}
               inset -4px -4px 10px 0 rgba(50, 50, 50,.5), inset 4px 4px 12px 0 rgba(0,0,0,.3);
             {% endif %}
        --soft-ui-shadow: {% if is_state('sun.sun', 'above_horizon') %}
              -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
            {% elif is_state('sun.sun', 'below_horizon') %}
              -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
            {% endif %}
      }
    styles:
      card:
        - font-family: 'Google Sans, Roboto'
        - font-weight: 500
        - background-color: var(--primary-background-color)
        - border-radius: 15px
        - box-shadow: var(--soft-ui-shadow)
      grid:
        - grid-template-areas: '"i i . ." "i i . ." ". . . ." "n n n ." "s . . ." ". . . ."'
        - grid-template-columns: 1fr 1fr 1fr 1fr
        - grid-template-rows: 1fr 1fr .25fr .75fr .75fr .75fr
        - padding: 15px
      icon:
        - color: var(--primary-text-color)
      name:
        - font-size: 20px
        - font-weight: 400
      state:
        - font-size: 20px
        - font-weight: 500
    type: 'custom:button-card'
  - aspect_ratio: 1/1
    entity: light.infinity_mirror
    show_state: true
    size: 80%
    state:
      - styles:
          card:
            - border-color: var(--primary-color)
            - border-width: 2px
            - box-shadow: var(--soft-ui-pressed)
          icon:
            - color: var(--primary-color)
          name:
            - color: var(--primary-color)
          state:
            - color: var(--primary-color)
        value: 'on'
    style: |
      #aspect-ratio {
        margin: 10px;
      }
      * {
        --soft-ui-pressed: {% if is_state('sun.sun', 'above_horizon') %}
               inset -4px -4px 8px 0 rgba(255,255,255,.5), inset 4px 4px 8px 0 rgba(0,0,0,.03);
             {% elif is_state('sun.sun', 'below_horizon') %}
               inset -4px -4px 10px 0 rgba(50, 50, 50,.5), inset 4px 4px 12px 0 rgba(0,0,0,.3);
             {% endif %}
        --soft-ui-shadow: {% if is_state('sun.sun', 'above_horizon') %}
              -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
            {% elif is_state('sun.sun', 'below_horizon') %}
              -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
            {% endif %}
      }
    styles:
      card:
        - font-family: 'Google Sans, Roboto'
        - font-weight: 500
        - background-color: var(--primary-background-color)
        - border-radius: 15px
        - box-shadow: var(--soft-ui-shadow)
      grid:
        - grid-template-areas: '"i i . ." "i i . ." ". . . ." "n n n ." "s . . ." ". . . ."'
        - grid-template-columns: 1fr 1fr 1fr 1fr
        - grid-template-rows: 1fr 1fr .25fr .75fr .75fr .75fr
        - padding: 15px
      icon:
        - color: var(--primary-text-color)
      name:
        - font-size: 20px
        - font-weight: 400
      state:
        - font-size: 20px
        - font-weight: 500
    type: 'custom:button-card'
```

**Comment by N-l1** [comment]
Still not working for me ☹️

Screen Shot 2020-08-04 at 8 51 32 PM
.

**Comment by KTibow** [comment]
@N-l1 the code only works in a smaller space, try a 2 item horizontal stack?

**Comment by KTibow** [comment]
BTW consider squah/merge when it's time

**Comment by N-l1** [comment]
I've added different variations of the button card. Thanks @KTibow!

**Pull request merged**
